<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260627143953 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE address (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, street VARCHAR(255) NOT NULL, building_number VARCHAR(20) NOT NULL, apartment_number VARCHAR(20) DEFAULT NULL, postal_code VARCHAR(20) NOT NULL, city VARCHAR(100) NOT NULL, country VARCHAR(100) NOT NULL, address_type VARCHAR(30) NOT NULL, company_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D4E6F81979B1AD6 ON address (company_id)');
        $this->addSql('CREATE TABLE cart (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, client_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BA388B719EB6921 ON cart (client_id)');
        $this->addSql('CREATE TABLE cart_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, unit_price_net NUMERIC(10, 2) NOT NULL, cart_id INT NOT NULL, product_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F0FE25271AD5CDBF ON cart_item (cart_id)');
        $this->addSql('CREATE INDEX IDX_F0FE25274584665A ON cart_item (product_id)');
        $this->addSql('CREATE TABLE category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, is_active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE client_registration_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, company_name VARCHAR(255) NOT NULL, tax_number VARCHAR(20) NOT NULL, company_email VARCHAR(255) NOT NULL, company_phone VARCHAR(30) DEFAULT NULL, billing_address_data JSON NOT NULL, delivery_address_data JSON NOT NULL, user_first_name VARCHAR(100) NOT NULL, user_last_name VARCHAR(100) NOT NULL, user_email VARCHAR(255) NOT NULL, password_hash VARCHAR(255) NOT NULL, status VARCHAR(30) NOT NULL, reviewed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, matched_customer_company_id INT DEFAULT NULL, reviewed_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EB441A222B35BD21 ON client_registration_request (matched_customer_company_id)');
        $this->addSql('CREATE INDEX IDX_EB441A22FC6B21F1 ON client_registration_request (reviewed_by_id)');
        $this->addSql('CREATE TABLE customer_company (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, tax_number VARCHAR(20) NOT NULL, email VARCHAR(255) NOT NULL, phone VARCHAR(30) DEFAULT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE customer_order (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, order_number VARCHAR(50) NOT NULL, status VARCHAR(30) NOT NULL, company_name VARCHAR(255) NOT NULL, company_tax_number VARCHAR(20) NOT NULL, delivery_address_snapshot TEXT DEFAULT NULL, customer_comment TEXT DEFAULT NULL, total_net NUMERIC(10, 2) NOT NULL, total_gross NUMERIC(10, 2) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, company_id INT NOT NULL, client_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3B1CE6A3979B1AD6 ON customer_order (company_id)');
        $this->addSql('CREATE INDEX IDX_3B1CE6A319EB6921 ON customer_order (client_id)');
        $this->addSql('CREATE TABLE order_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, product_name VARCHAR(255) NOT NULL, product_sku VARCHAR(64) NOT NULL, quantity INT NOT NULL, unit_price_net NUMERIC(10, 2) NOT NULL, vat_rate NUMERIC(5, 2) NOT NULL, total_net NUMERIC(10, 2) NOT NULL, total_gross NUMERIC(10, 2) NOT NULL, customer_order_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_52EA1F09A15A2E17 ON order_item (customer_order_id)');
        $this->addSql('CREATE TABLE product (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, sku VARCHAR(64) NOT NULL, description TEXT DEFAULT NULL, price_net NUMERIC(10, 2) NOT NULL, vat_rate NUMERIC(5, 2) NOT NULL, unit VARCHAR(20) NOT NULL, minimum_order_quantity INT NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, category_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D34A04AD12469DE2 ON product (category_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, company_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8D93D649979B1AD6 ON "user" (company_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('ALTER TABLE address ADD CONSTRAINT FK_D4E6F81979B1AD6 FOREIGN KEY (company_id) REFERENCES customer_company (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cart ADD CONSTRAINT FK_BA388B719EB6921 FOREIGN KEY (client_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cart_item ADD CONSTRAINT FK_F0FE25271AD5CDBF FOREIGN KEY (cart_id) REFERENCES cart (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cart_item ADD CONSTRAINT FK_F0FE25274584665A FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE client_registration_request ADD CONSTRAINT FK_EB441A222B35BD21 FOREIGN KEY (matched_customer_company_id) REFERENCES customer_company (id)');
        $this->addSql('ALTER TABLE client_registration_request ADD CONSTRAINT FK_EB441A22FC6B21F1 FOREIGN KEY (reviewed_by_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE customer_order ADD CONSTRAINT FK_3B1CE6A3979B1AD6 FOREIGN KEY (company_id) REFERENCES customer_company (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE customer_order ADD CONSTRAINT FK_3B1CE6A319EB6921 FOREIGN KEY (client_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_item ADD CONSTRAINT FK_52EA1F09A15A2E17 FOREIGN KEY (customer_order_id) REFERENCES customer_order (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD12469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649979B1AD6 FOREIGN KEY (company_id) REFERENCES customer_company (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE address DROP CONSTRAINT FK_D4E6F81979B1AD6');
        $this->addSql('ALTER TABLE cart DROP CONSTRAINT FK_BA388B719EB6921');
        $this->addSql('ALTER TABLE cart_item DROP CONSTRAINT FK_F0FE25271AD5CDBF');
        $this->addSql('ALTER TABLE cart_item DROP CONSTRAINT FK_F0FE25274584665A');
        $this->addSql('ALTER TABLE client_registration_request DROP CONSTRAINT FK_EB441A222B35BD21');
        $this->addSql('ALTER TABLE client_registration_request DROP CONSTRAINT FK_EB441A22FC6B21F1');
        $this->addSql('ALTER TABLE customer_order DROP CONSTRAINT FK_3B1CE6A3979B1AD6');
        $this->addSql('ALTER TABLE customer_order DROP CONSTRAINT FK_3B1CE6A319EB6921');
        $this->addSql('ALTER TABLE order_item DROP CONSTRAINT FK_52EA1F09A15A2E17');
        $this->addSql('ALTER TABLE product DROP CONSTRAINT FK_D34A04AD12469DE2');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649979B1AD6');
        $this->addSql('DROP TABLE address');
        $this->addSql('DROP TABLE cart');
        $this->addSql('DROP TABLE cart_item');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE client_registration_request');
        $this->addSql('DROP TABLE customer_company');
        $this->addSql('DROP TABLE customer_order');
        $this->addSql('DROP TABLE order_item');
        $this->addSql('DROP TABLE product');
        $this->addSql('DROP TABLE "user"');
    }
}
